# Site settings
title: Juan and Julia's Wedding
email: youremailaddress@gmail.com
description: Juan and Julia and getitng married
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://juanandjulia.com" # the base hostname & protocol for your site

# Social settings
#500px_url:
#facebook_url: https://facebook.com
#github_url:
#gitlab_url: https://gitlab.com/u/andrewbanchich
#googleplus_url: https://plus.google.com/u/0/+AndrewBanchich
#instagram_url: https://instagram.com
#linkedin_url: https://www.linkedin.com/in/andrew-banchich-a4ba1195
#pinterest_url:
#slack_url:
#twitter_url: https://twitter.com/andrewbanchich

# Build settings
markdown: kramdown
